config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boards
  resources :activities
  resources :countries
  resources :brands
  resources :campaigns

    root 'boards#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  
  validates :activity, :presence => true
	validates :brand, :presence => true
	validates :country, :presence => true
	validates :campaign, :presence => true

  
  
  
  belongs_to :campaign
  belongs_to :brand
  belongs_to :country
  belongs_to :activity
  belongs_to :user
  
  
  before_validation :sumar
  
  def sumar
    self.sum_time  = date_time.to_f - end_time.to_f
    
    self.sum_time = sum_time * 1 / 60
	        
	  self.sum_time = sum_time * -1
  end
  
  
  def self.search(search)
       
        if search   
            where(["date_time LIKE ?", "%#{search}%"])
        else
            all
        end
        
  end
  
  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |board|
      csv << board.attributes.values_at(*column_names)
     end
    end
  end
  
  
  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.search(params[:search])

    @board = current_user.boards.build
    
    
    respond_to do |format|
      format.html
      format.csv { send_data @boards.to_csv }
      format.xls # { send_data @boards.to_csv(col_sep: "\t") }

    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
        format.js
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:date_time, :campaign_id, :brand_id, :country_id, :activity_id, :end_time, :sum_time)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div id="board_<%= board.id %>">
  
  
  <% if current_user == User.find(1) %>
  


  <div class="jumbotron container">
  
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <b>User: </b><%= board.user.email %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <% if board.date_time > board.end_time  %>
       <i class="fa fa-exclamation fa-2x"> <p>ERROR DATE</p></i>
      <%end%>

      <b>Init time:</b>
      <%= board.date_time.to_formatted_s(:short)  %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">  
      <b>Campaign:</b>
      <%= board.campaign.campaign_name %>
    </div>
  </div>
   <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <b>Brand:</b>
      <%= board.brand.brand_name %>

    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
          
      <b>Country:</b>
      <%= board.country.country_name %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      
      <b>Activity:</b>
      <%= board.activity.activity_name %>
    </div>
  </div>
  
   
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-md-4 ">
             
      <b>End time:</b>
      <%= board.end_time.to_formatted_s(:short)  %>
     </div>
     <div class="col-xs-12 col-sm-6 col-md-4">
        <% if board.sum_time == nil ||  board.sum_time < 1 %>
          <i class="fa fa-exclamation fa-2x"> <p>ERROR TIME</p></i>
        <% elsif %>
          <b>Time Activity:</b>
          
          <% if board.sum_time == 1 %>
               <%= board.sum_time.round(0) %> Minute
          <% elsif%>
              <%= board.sum_time.round(0) %> Minutes
          <% end %>    
        <% end %>
     </div>
     <div class="col-xs-12 col-sm-6 col-md-4">
       
       <div class="col-xs-6 col-md-6">
          <h6> <em> Created <%= time_ago_in_words(board.created_at,include_seconds: true) %></em></h6>
       </div>
       
        <div class="col-xs-6 col-md-6">
          <div class="btn-group">
      	 
        		<!-- Button trigger modal -->
        	<button type="button" class="btn btn-default " data-toggle="modal" data-target="#myModal_<%= board.id %>">
        	  <i class="fa fa-pencil fa-2x"></i>
  
        	</button>
        	<%= link_to "<i class='fa fa-trash-o fa-2x'></i>".html_safe, board, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class:'btn btn-default ' %>
        
      	</div>
        </div>
       
      	
     </div>
   </div>
   
   

</div>
  
  
  
  
  
  
  <% elsif current_user == board.user  %>
  
  
 
  
<div class="jumbotron container" id="muevemueve">
  
    <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <b>User: </b><%= board.user.email %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <% if board.date_time > board.end_time  %>
       <i class="fa fa-exclamation fa-2x"> <p>ERROR DATE</p></i>
      <%end%>

      <b>Init time:</b>
      <%= board.date_time.to_formatted_s(:short) %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">  
      <b>Campaign:</b>
      <%= board.campaign.campaign_name %>
    </div>
  </div>
   <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <b>Brand:</b>
      <%= board.brand.brand_name %>

    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
          
      <b>Country:</b>
      <%= board.country.country_name %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      
      <b>Activity:</b>
      <%= board.activity.activity_name %>
    </div>
  </div>
  
   
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-md-4 ">
             
      <b>End time:</b>
      <%= board.end_time.to_formatted_s(:short) %>
     </div>
     <div class="col-xs-12 col-sm-6 col-md-4">
        <% if board.sum_time == nil ||  board.sum_time < 1 %>
          <i class="fa fa-exclamation fa-2x"> <p>ERROR TIME</p></i>
        <% elsif %>
          <b>Time Activity:</b>
          
          <% if board.sum_time == 1 %>
               <%= board.sum_time.round(0) %> Minute
          <% elsif%>
              <%= board.sum_time.round(0) %> Minutes
          <% end %> 

        <% end %>
     </div>
     <div class="col-xs-12 col-sm-6 col-md-4">
       
       <div class="col-xs-6 col-md-6">
         <h6> <em> Created <%= time_ago_in_words(board.created_at,include_seconds: true) %></em></h6>
       </div>
       
        <div class="col-xs-6 col-md-6">
          <div class="btn-group">
      	 
        		<!-- Button trigger modal -->
        	<button type="button" class="btn btn-default " data-toggle="modal" data-target="#myModal_<%= board.id %>">
        	  <i class="fa fa-pencil fa-2x"></i>
  
        	</button>
        	<%= link_to "<i class='fa fa-trash-o fa-2x'></i>".html_safe, board, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class:'btn btn-default ' %>
        
      	</div>
        </div>
       
      	
     </div>
   </div>
   

</div>


  <%end%>
    

	<%= form_for(board, :method => :put, remote: true) do |f| %>

	<!-- Modal -->
	<div class="modal fade" id="myModal_<%= board.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">Edit</h4>
	      </div>
	      <div class="modal-body">
	        
	        
	        
      <div class="field">
     Init time<br>
    <%= f.datetime_select :date_time, class:'board_datetime form-control' %>
  </div>
  
  
  <div class="field">
       Campaign <br>                    
      <%= f.collection_select :campaign_id, Campaign.all, :id, :campaign_name, {prompt: "Select Campaign"},{class: "form-control board_campaign"} %>
  </div>

   <div class="field">
       Brand <br>                    
      <%= f.collection_select :brand_id, Brand.all, :id, :brand_name, {prompt: "Select Brand"},{class: "form-control board_brand"} %>
  </div>
  
  <div class="field">
       Country <br>                    
      <%= f.collection_select :country_id, Country.all, :id, :country_name, {prompt: "Select Country"},{class: "form-control board_country"} %>
  </div>
 
 <div class="field">
       Activity <br>                    
      <%= f.collection_select :activity_id, Activity.all, :id, :activity_name, {prompt: "Select Activity"},{class: "form-control board_activity"} %>
  </div>
 
  <div class="field">
    End time<br>
    <%= f.datetime_select :end_time, class:'board_endtime form-control' %>
  </div>
  <div class="field" >
<br>
    <%= f.text_field :sum_time, class:'board_sumtime' , class:'invisible' %>
  </div>
   
	        
	        
	      </div>
	      <div class="modal-footer">
	             <%= f.submit "Save", class:'btn btn-default btn-lg btn-block' %>

	      </div>
	    </div>
	  </div>
	</div>


<% end %>

</div>

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_time %><br>
    <%= f.datetime_select :date_time %>
  </div>
  
  
  <div class="field">
       Campaign <br>                    
      <%= f.collection_select :campaign_id, Campaign.all, :id, :campaign_name, {prompt: "Select Campaign"},{class: "form-control"} %>
  </div>

   <div class="field">
       Brand <br>                    
      <%= f.collection_select :brand_id, Brand.all, :id, :brand_name, {prompt: "Select Brand"},{class: "form-control"} %>
  </div>
  
  <div class="field">
       Country <br>                    
      <%= f.collection_select :country_id, Country.all, :id, :country_name, {prompt: "Select Country"},{class: "form-control"} %>
  </div>
 
 <div class="field">
       Activity <br>                    
      <%= f.collection_select :activity_id, Activity.all, :id, :activity_name, {prompt: "Select Activity"},{class: "form-control"} %>
  </div>
 
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :sum_time %><br>
    <%= f.text_field :sum_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/create.js.erb
$("#myModal").modal('hide');
$(".board_datetime").val('');
$(".board_campaign").val('');
$(".board_brand").val('');
$(".board_country").val('');
$(".board_activity").val('');
$(".board_endtime").val('');
$(".board_sumtime").val('');

$("#container_boards").prepend('<%= j render @board %>');
$("#board_<%= @board.id %>").hide().fadeIn(1000);

app/views/boards/destroy.js.erb
$("#board_<%= @board.id %>").fadeOut(500, function(){
	$(this).remove();
});

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<body class="board">
  
  <header class="navbar">
  <div class="container1">
  
   <a type="button" class="fa fa-plus fa-3x" data-toggle="modal" data-target="#myModal"></a>
    
   <% if current_user == User.find(1) %>
     <%= link_to "<i class='fa fa-file-excel-o fa-3x'></i>".html_safe, boards_path(format: "xls") %> 
   <%end%>
    <%= link_to  "<i class='fa fa-user-times fa-3x  logosalir'> </i> ".html_safe, destroy_user_session_path, :method => :delete %>
   <% if current_user == User.find(1) %>
      <%= link_to 'Campaigns', campaigns_path %>
      <%= link_to 'Activities', activities_path %>
      <%= link_to 'Brands', brands_path %>
      <%= link_to 'Countries', countries_path %>
   <% end %>
  </div>
</header>

  <!-- Button trigger modal -->
<br></br> <br>


<div class="container">
  <div class="row">
    <%= form_tag boards_path, :method => 'get' do %>
      <div class="col-xs-12 col-md-4"></div>
      
     <div class="col-xs-12  col-md-4 ">
       
       <div class="col-xs-6 col-md-6">
        <%= text_field_tag :search, params[:search], class:'form-control'%>
       </div>
       
       <div class="col-xs-6 col-md-6">
         <%= submit_tag "Search By Day", class:'btn btn-default' %>
       </div>
       
        
     </div>
     
     
    <% end %>
    
    <div class="col-xs-12 col-md-4">
      
      <% if current_user == User.find(1)%>
      
        <h4 class="derecho"><span class="badge"> <%= @boards.count %> </span></h4 >
      
      <% end %>

    </div>
  </div>
</div>

<br>
<div  id="container_boards">
  
  <%= render @boards %>
</div>


<!-- Modal -->
<%= form_for(@board, remote: true) do |f| %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Boards</h4>
    </div>
    <div class="modal-body">
   
      <div class="field">
     Init time<br>
    <%= f.datetime_select :date_time, class:'board_datetime form-control' %>
  </div>
  
  
  <div class="field">
       Campaign <br>                    
      <%= f.collection_select :campaign_id, Campaign.all, :id, :campaign_name, {prompt: "Select Campaign"},{class: "form-control board_campaign"} %>
  </div>

   <div class="field">
       Brand <br>                    
      <%= f.collection_select :brand_id, Brand.all, :id, :brand_name, {prompt: "Select Brand"},{class: "form-control board_brand"} %>
  </div>
  
  <div class="field">
       Country <br>                    
      <%= f.collection_select :country_id, Country.all, :id, :country_name, {prompt: "Select Country"},{class: "form-control board_country"} %>
  </div>
 
 <div class="field">
       Activity <br>                    
      <%= f.collection_select :activity_id, Activity.all, :id, :activity_name, {prompt: "Select Activity"},{class: "form-control board_activity"} %>
  </div>
 
  <div class="field">
    End time<br>
    <%= f.datetime_select :end_time, class:'board_endtime form-control' %>
  </div>
  <div class="field">
 <br>
    <%= f.text_field :sum_time, class:'board_sumtime', class:'invisible'%>
  </div>
   
   
   
   
   
      </div>
    <div class="modal-footer">
      <%= f.submit "Save", class:'btn btn-default btn-lg btn-block' %>
    </div>
  </div>
</div>
</div>
<% end %>


</body>

app/views/boards/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Id</Data></Cell>
        <Cell><Data ss:Type="String">User</Data></Cell>
        <Cell><Data ss:Type="String">Init time</Data></Cell>
        <Cell><Data ss:Type="String">Campaign</Data></Cell>
        <Cell><Data ss:Type="String">Brand</Data></Cell>
        <Cell><Data ss:Type="String">Country</Data></Cell>
        <Cell><Data ss:Type="String">Activity</Data></Cell>
        <Cell><Data ss:Type="String">End time</Data></Cell>
        <Cell><Data ss:Type="String">Minutes</Data></Cell>
      </Row>
    <% @boards.each do |board| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= board.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.date_time.to_formatted_s(:short) %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.campaign.campaign_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.brand.brand_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.country.country_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.activity.activity_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= board.end_time.to_formatted_s(:short) %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= board.sum_time.round(0) %></Data></Cell>
        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date time:</strong>
  <%= @board.date_time %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @board.campaign.campaign_name %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @board.brand.brand_name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @board.country.country_name %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @board.activity.activity_name %>
</p>

<p>
  <strong>End time:</strong>
  <%= @board.end_time %>
</p>

<p>
  <strong>Sum time:</strong>
  <%= @board.sum_time %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/boards/update.js.erb
$("#myModal_<%= @board.id %>").modal('hide');
$("#board_<%= @board.id %>").fadeOut(500, function(){

	$(this).remove();
	$("#container_boards").prepend('<%= j render @board %>');

});